#!/usr/bin/env python3
"""Convert the ERG's grammar-error table (grammar/erg/educ/ParserErrorCodes.xlsx)
to errors.tsv: one row per error code (a rule, lexical entry, lexical type or
root name of the ERG's mal-rule configuration).

Columns: code, error class, feedback text (English; `$X` stands for the
word), example sentences (separated by ` | `).

Usage: python3 gen-errors.py ../../grammar/erg/educ/ParserErrorCodes.xlsx > errors.tsv
"""
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}


def text(el):
    return "".join(t.text or "" for t in el.iter("{%s}t" % NS["m"]))


def rows(path):
    z = zipfile.ZipFile(path)
    shared = [text(si) for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", NS)]
    sheet = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    for r in sheet.iter("{%s}row" % NS["m"]):
        vals = {}
        for c in r.findall("m:c", NS):
            col = re.match(r"[A-Z]+", c.get("r")).group()
            v = c.find("m:v", NS)
            if v is None:
                inline = c.find("m:is", NS)
                vals[col] = text(inline) if inline is not None else ""
            else:
                vals[col] = shared[int(v.text)] if c.get("t") == "s" else v.text
        yield vals


def clean(s):
    return " ".join((s or "").split())


def main():
    out = ["# code\tclass\tfeedback\texamples; generated by gen-errors.py, see SOURCE.md"]
    seen = set()
    for i, r in enumerate(rows(sys.argv[1])):
        if i == 0:
            continue
        feedback = clean(r.get("B"))
        if not feedback:
            continue
        examples = " | ".join(clean(x) for x in (r.get("D") or "").split("\n") if clean(x))
        for code in re.split(r"[,\s]+", r.get("A") or ""):
            code = code.strip()
            if not code or code in seen:
                continue
            seen.add(code)
            out.append("\t".join([code, clean(r.get("H")), feedback, examples]))
    print("\n".join(out))


if __name__ == "__main__":
    main()
