[package]
name = "emdysi-parse"
description = "English parsing pipeline running the English Resource Grammar"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
emdysi-tdl = { path = "../emdysi-tdl" }
emdysi-hpsg = { path = "../emdysi-hpsg" }
emdysi-repp = { path = "../emdysi-repp" }

[lints]
workspace = true
