#!/usr/bin/env python3
"""Generate rule packs from vendored third-party rule data.

Converts the `existence` and `substitution` rules of the vendored Vale
packages (data/vale/<name>/) and the word lists of data/words/ into emdysi
rule packs (packs/<name>.toml). Other Vale rule kinds (capitalization,
conditional, sequence, ...) and rules scoped to raw markup or code are
skipped: emdysi has its own rules for those concerns.

    python3 scripts/import-rules.py           # write the packs
    python3 scripts/import-rules.py --check   # fail if a pack is out of date

The generated packs are registered in VENDORED.toml; do not edit them by
hand.
"""

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

VALE = [
    # (pack, directory, styles subdirectory, description, attribution)
    (
        "microsoft",
        "data/vale/microsoft",
        "Microsoft",
        "Word choice from the Microsoft Writing Style Guide, from the Vale "
        "package errata-ai/Microsoft (opt-in).",
        "errata-ai/Microsoft (MIT, Copyright (c) 2018 - 2019 Joseph Kato); "
        "rules implement the Microsoft Writing Style Guide (CC BY 4.0, "
        "Microsoft Corporation). Not maintained or endorsed by Microsoft.",
    ),
    (
        "google",
        "data/vale/google",
        "Google",
        "Word choice from the Google developer documentation style guide, "
        "from the Vale package errata-ai/Google (opt-in).",
        "errata-ai/Google (MIT, Copyright (c) 2018 - 2019 Joseph Kato); "
        "rules implement the Google developer documentation style guide "
        "(CC BY 4.0, Google LLC). Not maintained or endorsed by Google.",
    ),
    (
        "elastic",
        "data/vale/elastic",
        "Elastic",
        "Word choice from the Elastic style guide, from the Vale package "
        "elastic/vale-rules (opt-in).",
        "elastic/vale-rules (Apache-2.0, Copyright 2025 Elasticsearch B.V.; "
        "see data/vale/elastic/NOTICE.txt).",
    ),
]

WORDS = [
    # (list, severity, message, description)
    (
        "hedges",
        "suggestion",
        "Hedge '{match}'; say how sure you are, or why.",
        "Hedge words and phrases, from the `hedges` list (words/hedges).",
    ),
    (
        "weasels",
        "suggestion",
        "Weasel word '{match}'; be specific.",
        "Weasel words, from the `weasels` list (words/weasels).",
    ),
    (
        "fillers",
        "suggestion",
        "Filler '{match}'; cut it if the sentence works without it.",
        "Filler words, from the `fillers` list (words/fillers).",
    ),
]

SEVERITY = {"error": "error", "warning": "warning", "suggestion": "suggestion"}


def kebab(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "-", name).lower()


def q(s):
    """A TOML basic string."""
    out = []
    for c in s:
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "\n":
            out.append("\\n")
        elif c == "\t":
            out.append("\\t")
        elif ord(c) < 0x20:
            out.append("\\u%04x" % ord(c))
        else:
            out.append(c)
    return '"' + "".join(out) + '"'


def literal(tok):
    """Whether a token is plain words (usable in a generated example)."""
    return re.fullmatch(r"[A-Za-z][A-Za-z' ]*[A-Za-z]", tok) is not None


def message(msg, kind):
    """Vale's %s placeholders as emdysi's: existence (match), substitution
    (replacement, match)."""
    msg = msg.replace("%%", "%")
    names = ["{match}"] if kind == "existence" else ["{replacement}", "{match}"]
    for n in names:
        msg = msg.replace("%s", n, 1)
    return msg.replace("%s", "{match}")


def vale_pack(name, directory, styles, description, attribution):
    base = ROOT / directory
    lines = [
        "# Generated by scripts/import-rules.py from " + directory + "; do not edit.",
        "# Source: " + attribution,
        "",
        "[pack]",
        "name = " + q(name),
        "description = " + q(description),
    ]
    skipped = []
    for f in sorted((base / styles).glob("*.yml")):
        r = yaml.safe_load(f.read_text(encoding="utf-8"))
        kind = r.get("extends")
        scope = r.get("scope", "text")
        if isinstance(scope, list):
            scope = scope[0] if len(scope) == 1 else "text"
        if kind not in ("existence", "substitution") or scope in ("raw", "code") or r.get("raw"):
            skipped.append(f.stem)
            continue
        out = [
            "",
            "[[rule]]",
            "id = " + q(name + "." + kebab(f.stem)),
            "kind = " + q(kind),
            "severity = " + q(SEVERITY.get(r.get("level", "suggestion"), "suggestion")),
            "message = " + q(message(r.get("message", f.stem), kind)),
        ]
        if r.get("description"):
            out.append("description = " + q(str(r["description"]).strip()))
        if scope == "heading":
            out.append('scope = "heading"')
        elif scope == "sentence":
            out.append('scope = "body"')
        src = r.get("link") or ""
        out.append("source = " + q((src + "; " if src else "") + f"{directory}/{styles}/{f.name}"))
        out.append("license = " + q(attribution))
        if r.get("ignorecase"):
            out.append("ignorecase = true")
        if r.get("nonword"):
            out.append("nonword = true")
        example = None
        if kind == "existence":
            tokens = [str(t) for t in r.get("tokens") or []]
            if not tokens:
                skipped.append(f.stem)
                continue
            out.append("tokens = [")
            out.extend("  " + q(t) + "," for t in tokens)
            out.append("]")
            exc = [str(e) for e in r.get("exceptions") or []]
            if exc:
                out.append("exceptions = [" + ", ".join(q(e) for e in exc) + "]")
            example = next((t for t in tokens if literal(t) and t not in exc), None)
        else:
            swap = r.get("swap") or {}
            if not swap:
                skipped.append(f.stem)
                continue
            items = [(str(k), str(v)) for k, v in swap.items()]
            example = next(
                (k for k, v in items if literal(k) and k not in v.split("|")), None
            )
            if example:
                out.append("examples = [" + q(example_doc(example, scope)) + "]")
            # The swap table comes last: its header opens a new table.
            out.append("[rule.swap]")
            out.extend(q(k) + " = " + q(v) for k, v in items)
            lines.extend(out)
            continue
        if example:
            out.append("examples = [" + q(example_doc(example, scope)) + "]")
        lines.extend(out)
    lines.append("")
    if skipped:
        lines.insert(2, "# Skipped (other Vale kinds, or raw/code scope): " + ", ".join(skipped))
    return "\n".join(lines)


def example_doc(tok, scope):
    if scope == "heading":
        return f"# Notes\n\nText.\n\n## {tok[0].upper() + tok[1:]}\n\nText.\n"
    return f"We saw {tok} in the draft.\n"


def word_list(name):
    words = []
    for line in (ROOT / "data/words" / name / "data.txt").read_text(encoding="utf-8").splitlines():
        line = line.split("%", 1)[0].strip()
        if line:
            words.append(line)
    return words


def words_pack():
    lines = [
        "# Generated by scripts/import-rules.py from data/words; do not edit.",
        "# Source: words/hedges, words/weasels, words/fillers (MIT, "
        "Copyright (c) 2014 Titus Wormer).",
        "",
        "[pack]",
        'name = "wordlists"',
        'description = "Hedges, weasel words and fillers from the words/* lists (opt-in)."',
    ]
    for name, severity, msg, desc in WORDS:
        words = word_list(name)
        lines += [
            "",
            "[[rule]]",
            "id = " + q("wordlists." + name),
            'kind = "words"',
            'match = "surface"',
            "severity = " + q(severity),
            "message = " + q(msg),
            "description = " + q(desc),
            "source = " + q(f"https://github.com/words/{name}; data/words/{name}/data.txt"),
            'license = "MIT, Copyright (c) 2014 Titus Wormer"',
            "examples = [" + q(f"We saw {next(w for w in words if literal(w))} in the draft.\n") + "]",
            "words = [",
        ]
        lines += ["  " + q(w) + "," for w in words]
        lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    outputs = {f"packs/{v[0]}.toml": vale_pack(*v) for v in VALE}
    outputs["packs/wordlists.toml"] = words_pack()
    stale = []
    for path, text in outputs.items():
        p = ROOT / path
        if check:
            if not p.exists() or p.read_text(encoding="utf-8") != text:
                stale.append(path)
        else:
            p.write_text(text, encoding="utf-8")
            print("wrote", path)
    if stale:
        print("out of date (run scripts/import-rules.py):", ", ".join(stale))
        sys.exit(1)
    if check:
        print("ok:", len(outputs), "packs up to date")


if __name__ == "__main__":
    main()
